# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.4.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
branches:
  except:
    - dev
after_success:
- julia -e 'cd(Pkg.dir("BEE")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
